const PE=window.PatternEngine;
const $=q=>document.querySelector(q);
const $$=q=>[...document.querySelectorAll(q)];
const canvas=$('#previewCanvas'),ctx=canvas.getContext('2d');
const palettePresets=[
  ['#FFF8FC','#F7B9D7','#B7D5FF','#D7C2FF'],['#FFF9F3','#FFD7A8','#FFB8C8','#BFE6D3'],['#F7F5FF','#AFA0F4','#D5C9FF','#9EDAE3'],['#FFF8F2','#F3AFA7','#F7D68B','#AECFBA'],
  ['#F7FAFF','#A9C9FF','#BBDCF4','#D9C7FF'],['#FFF8F8','#EFA3B5','#B9D8B4','#F0D78F'],['#FAF7FF','#D7B8FF','#B5E1DE','#FFC6D9'],['#FFF9EC','#F2C572','#F2A4A4','#9FCBC4']
];
const initial={presetId:'pastel-checker',colors:['#FFF9FC','#F5B9D4','#B9D7FF','#BFAAF2'],size:72,gap:24,jitter:18,rotation:0,stroke:4,opacity:100,detail:45,seed:Date.now()%1000000,bgMode:'solid',gradientAngle:135,transparentBg:false,exportW:2000,exportH:2000};
let state={...initial,colors:[...initial.colors]},zoom=1,activeCategory='전체';
const colorMeta=[['배경 A','배경/주색'],['패턴 A','첫 번째 패턴색'],['패턴 B','두 번째 패턴색'],['포인트','포인트/디테일색']];

function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1700)}
function preset(){return PE.presets.find(p=>p.id===state.presetId)||PE.presets[0]}
function categories(){return ['전체',...new Set(PE.presets.map(p=>p.category))]}
function renderMain(){PE.render(ctx,canvas.width,canvas.height,state,preset(),canvas.width/2000);updateSelected()}
function updateSelected(){let p=preset();$('#selectedCategory').textContent=p.category;$('#selectedName').textContent=p.name;$('#selectedDesc').textContent=p.desc}
function setupCategories(){let wrap=$('#categoryTabs');wrap.innerHTML='';categories().forEach(c=>{let b=document.createElement('button');b.className='tab'+(c===activeCategory?' active':'');b.textContent=c;b.onclick=()=>{activeCategory=c;setupCategories();renderPatternList()};wrap.appendChild(b)})}
function filteredPresets(){let q=$('#searchInput').value.trim().toLowerCase();return PE.presets.filter(p=>(activeCategory==='전체'||p.category===activeCategory)&&(!q||`${p.name} ${p.category} ${p.desc} ${p.id}`.toLowerCase().includes(q)))}
function thumbnailState(p){let d=PE.defaults[p.id]||{};return{...state,...d,rotation:0,jitter:d.jitter??state.jitter,opacity:100,detail:d.detail??state.detail,size:d.size??70,gap:d.gap??24,stroke:d.stroke??4}}
function renderPatternList(){let list=$('#patternList'),items=filteredPresets();$('#patternCount').textContent=`${PE.presets.length}가지 패턴 · 현재 ${items.length}개`;list.innerHTML='';items.forEach(p=>{let b=document.createElement('button');b.className='pattern-card'+(p.id===state.presetId?' active':'');let c=document.createElement('canvas');c.width=c.height=180;PE.render(c.getContext('2d'),180,180,thumbnailState(p),p,180/720);let st=document.createElement('strong');st.textContent=p.name;let sm=document.createElement('small');sm.textContent=p.desc;b.append(c,st,sm);b.onclick=()=>selectPattern(p.id);list.appendChild(b)})}
function selectPattern(id){state.presetId=id;let d=PE.defaults[id]||{};Object.assign(state,d);syncControls();renderMain();renderPatternList()}
function setupColors(){let grid=$('#colorGrid');grid.innerHTML='';colorMeta.forEach((m,i)=>{let wrap=document.createElement('div');wrap.className='color-row';let label=document.createElement('div');label.className='color-label';label.textContent=`${m[0]} · ${m[1]}`;let picker=document.createElement('input');picker.type='color';picker.value=state.colors[i];picker.dataset.ci=i;let text=document.createElement('input');text.type='text';text.value=state.colors[i];text.maxLength=7;text.dataset.hex=i;let drop=document.createElement('button');drop.className='dropper';drop.type='button';drop.textContent='💧';drop.title='화면에서 색상 추출';drop.dataset.drop=i;wrap.append(label,picker,text,drop);grid.appendChild(wrap)});grid.oninput=e=>{let t=e.target;if(t.dataset.ci!==undefined){let i=+t.dataset.ci;state.colors[i]=t.value.toUpperCase();grid.querySelector(`[data-hex="${i}"]`).value=state.colors[i];renderMain();renderPatternListDebounced()}if(t.dataset.hex!==undefined&&/^#[0-9a-fA-F]{6}$/.test(t.value)){let i=+t.dataset.hex;state.colors[i]=t.value.toUpperCase();grid.querySelector(`[data-ci="${i}"]`).value=state.colors[i];renderMain();renderPatternListDebounced()}};grid.onclick=async e=>{let t=e.target.closest('[data-drop]');if(!t)return;let i=+t.dataset.drop;if(!window.EyeDropper){toast('이 브라우저는 화면 스포이드를 지원하지 않아. 컬러피커나 HEX 입력을 이용해줘.');return}try{let r=await new EyeDropper().open();state.colors[i]=r.sRGBHex.toUpperCase();setupColors();renderMain();renderPatternList()}catch{}};}
function setupPalettes(){let w=$('#palettePresets');w.innerHTML='';palettePresets.forEach((pal,idx)=>{let b=document.createElement('button');b.className='palette-chip';b.title=`팔레트 ${idx+1}`;pal.forEach(c=>{let i=document.createElement('i');i.style.background=c;b.appendChild(i)});b.onclick=()=>{state.colors=[...pal];setupColors();renderMain();renderPatternList()};w.appendChild(b)})}
function syncControls(){[['size','size','px'],['gap','gap','px'],['jitter','jitter','%'],['rotation','rotation','°'],['stroke','stroke','px'],['opacity','opacity','%'],['detail','detail','%'],['gradientAngle','gradientAngle','°']].forEach(([id,key,u])=>{let el=$('#'+id);el.value=state[key];$('#'+id+'Val').textContent=`${state[key]}${u}`});$('#bgMode').value=state.bgMode;$('#transparentBg').checked=state.transparentBg;$('#gradientControls').style.display=state.bgMode==='linear'&&!state.transparentBg?'block':'none';$('#exportW').value=state.exportW;$('#exportH').value=state.exportH;setupColors()}
let thumbTimer;function renderPatternListDebounced(){clearTimeout(thumbTimer);thumbTimer=setTimeout(renderPatternList,180)}
function setupControls(){['size','gap','jitter','rotation','stroke','opacity','detail','gradientAngle'].forEach(id=>{$('#'+id).addEventListener('input',e=>{state[id]=+e.target.value;$('#'+id+'Val').textContent=e.target.value+(id==='rotation'||id==='gradientAngle'?'°':id==='size'||id==='gap'||id==='stroke'?'px':'%');renderMain();renderPatternListDebounced()})});$('#bgMode').onchange=e=>{state.bgMode=e.target.value;syncControls();renderMain();renderPatternList()};$('#transparentBg').onchange=e=>{state.transparentBg=e.target.checked;syncControls();renderMain();renderPatternList()};$('#randomSeed').onclick=()=>{state.seed=Math.floor(Math.random()*1e9);renderMain();renderPatternList();toast('새로운 불규칙 배치를 만들었어.')};$('#paletteShuffle').onclick=()=>{state.colors=[state.colors[0],...shuffle(state.colors.slice(1))];setupColors();renderMain();renderPatternList()};$('#randomizeAll').onclick=randomizeAll;$('#resetBtn').onclick=()=>{state={...initial,colors:[...initial.colors],seed:Date.now()%1000000};activeCategory='전체';syncControls();setupCategories();renderMain();renderPatternList();toast('초기 상태로 되돌렸어.')};$('#searchInput').oninput=renderPatternList;$('#exportW').oninput=e=>{state.exportW=clamp(+e.target.value||2000,256,6000);if($('#lockSquare').checked){state.exportH=state.exportW;$('#exportH').value=state.exportH}};$('#exportH').oninput=e=>{state.exportH=clamp(+e.target.value||2000,256,6000);if($('#lockSquare').checked){state.exportW=state.exportH;$('#exportW').value=state.exportW}};$('#exportBtn').onclick=exportPNG;$('#exportBtn2').onclick=exportPNG;$('#zoomIn').onclick=()=>setZoom(zoom+.1);$('#zoomOut').onclick=()=>setZoom(zoom-.1)}
function setZoom(v){zoom=clamp(v,.3,1.6);$('#zoomText').textContent=Math.round(zoom*100)+'%';canvas.style.width=`min(${72*zoom}vh, ${78*zoom}vw)`}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function randomizeAll(){let ps=filteredPresets();if(!ps.length)ps=PE.presets;selectPattern(ps[Math.floor(Math.random()*ps.length)].id);let pal=palettePresets[Math.floor(Math.random()*palettePresets.length)];state.colors=[...pal];state.size=Math.floor(35+Math.random()*95);state.gap=Math.floor(6+Math.random()*65);state.jitter=Math.floor(Math.random()*70);state.rotation=Math.floor(-18+Math.random()*36);state.detail=Math.floor(25+Math.random()*70);state.seed=Math.floor(Math.random()*1e9);syncControls();renderMain();renderPatternList();toast('패턴·색·배치를 랜덤 조합했어.')}
async function exportPNG(){let w=clamp(+$('#exportW').value||2000,256,6000),h=clamp(+$('#exportH').value||2000,256,6000);state.exportW=w;state.exportH=h;let out=document.createElement('canvas');out.width=w;out.height=h;let octx=out.getContext('2d');PE.render(octx,w,h,state,preset(),w/2000);let blob=await new Promise(r=>out.toBlob(r,'image/png'));if(!blob){toast('PNG 생성에 실패했어.');return}let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cute-pattern-${preset().id}-${w}x${h}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast(`${w}×${h} PNG를 저장했어.`)}

setupCategories();setupPalettes();setupControls();syncControls();renderMain();renderPatternList();
