
const PE=window.PatternEngine;
const $=q=>document.querySelector(q);
const canvas=$('#previewCanvas'),ctx=canvas.getContext('2d');
const palettePresets=[
  ['#FFF8FC','#F7B9D7','#B7D5FF','#D7C2FF'],['#FFF9F3','#FFD7A8','#FFB8C8','#BFE6D3'],['#F7F5FF','#AFA0F4','#D5C9FF','#9EDAE3'],['#FFF8F2','#F3AFA7','#F7D68B','#AECFBA'],
  ['#F7FAFF','#A9C9FF','#BBDCF4','#D9C7FF'],['#FFF8F8','#EFA3B5','#B9D8B4','#F0D78F'],['#FAF7FF','#D7B8FF','#B5E1DE','#FFC6D9'],['#FFF9EC','#F2C572','#F2A4A4','#9FCBC4']
];
const STORAGE={state:'cps-v03-state',favorites:'cps-v03-favorites',presets:'cps-v03-presets',assets:'cps-v03-assets'};
const colorMeta=[['배경 A','주 배경/기본색'],['패턴 A','패턴 기본색'],['패턴 B','서브 패턴색'],['포인트','포인트/디테일색']];
const defaultBg=['#FFF9FC','#F5B9D4'];
let zoom=1,activeCategory='전체',activeLayerIndex=0,thumbTimer=0,referencePalette=[];

function uid(prefix='id'){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`}
function clone(v){return JSON.parse(JSON.stringify(v))}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function shuffle(a){let out=[...a];for(let i=out.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function toast(msg){let el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),1800)}
function categories(){return ['전체',...new Set(PE.presets.map(p=>p.category))]}
function getPreset(id){return PE.presets.find(p=>p.id===id)||PE.presets[0]}
function defaultLayer(i,presetId='pastel-checker',enabled=true){return {enabled,name:`레이어 ${i+1}`,sourceType:'builtin',presetId,assetId:'',renderMode:'motif',colors:['#FFF9FC','#F5B9D4','#B9D7FF','#BFAAF2'],size:i===0?72:(i===1?58:44),gap:i===0?24:28,jitter:i===0?18:22,rotation:0,stroke:4,opacity:i===0?100:(i===1?70:55),detail:45,seed:Math.floor(Math.random()*1e9),svgColorMode:'original'}}
function makeInitialState(){return {bg:{transparent:false,mode:'solid',colors:[...defaultBg],gradientAngle:135},exportW:2000,exportH:2000,tileW:512,tileH:512,layers:[defaultLayer(0,'pastel-checker',true),defaultLayer(1,'tiny-dot',true),defaultLayer(2,'sparkles',false)]}}
let favorites=new Set();
let myPresets=[];
let userAssets=[];
let state=makeInitialState();

function loadLocal(){
  try{favorites=new Set(JSON.parse(localStorage.getItem(STORAGE.favorites)||'[]'))}catch{}
  try{myPresets=JSON.parse(localStorage.getItem(STORAGE.presets)||'[]')||[]}catch{}
  try{userAssets=JSON.parse(localStorage.getItem(STORAGE.assets)||'[]')||[]}catch{}
  try{let saved=JSON.parse(localStorage.getItem(STORAGE.state)||'null');if(saved)state=mergeState(saved)}catch{}
}
function mergeState(saved){let base=makeInitialState();if(!saved||typeof saved!=='object')return base;let merged={...base,...saved,bg:{...base.bg,...(saved.bg||{})}};merged.layers=(saved.layers||base.layers).slice(0,3).map((l,i)=>({...defaultLayer(i),...l,colors:[...(l.colors||defaultLayer(i).colors)]}));while(merged.layers.length<3)merged.layers.push(defaultLayer(merged.layers.length));return merged}
function persistAll(){localStorage.setItem(STORAGE.favorites,JSON.stringify([...favorites]));localStorage.setItem(STORAGE.presets,JSON.stringify(myPresets));localStorage.setItem(STORAGE.assets,JSON.stringify(stripAssetCache(userAssets)));localStorage.setItem(STORAGE.state,JSON.stringify(stripStateForSave(state)))}
function stripStateForSave(s){let copy=clone(s);return copy}
function stripAssetCache(arr){return arr.map(a=>{let c={...a};delete c._img;delete c._cacheKey;return c})}

function currentLayer(){return state.layers[activeLayerIndex]}
function layerTitle(layer,idx){if(layer.sourceType==='builtin'){let p=getPreset(layer.presetId);return `${layer.name} · ${p.name}`}let a=userAssets.find(v=>v.id===layer.assetId);return `${layer.name} · ${a?a.name:'업로드 에셋 없음'}`}

function drawBackground(target,w,h){if(state.bg.transparent){target.clearRect(0,0,w,h);return}target.clearRect(0,0,w,h);if(state.bg.mode==='linear'){let a=(state.bg.gradientAngle||135)*Math.PI/180,cx=w/2,cy=h/2,L=Math.abs(w*Math.cos(a))+Math.abs(h*Math.sin(a)),dx=Math.cos(a)*L/2,dy=Math.sin(a)*L/2;let g=target.createLinearGradient(cx-dx,cy-dy,cx+dx,cy+dy);g.addColorStop(0,state.bg.colors[0]);g.addColorStop(1,state.bg.colors[1]);target.fillStyle=g}else target.fillStyle=state.bg.colors[0];target.fillRect(0,0,w,h)}
function layerToPatternState(layer,seamless=false){return {presetId:layer.presetId,colors:[...layer.colors],size:layer.size,gap:layer.gap,jitter:seamless?0:layer.jitter,rotation:layer.rotation,stroke:layer.stroke,opacity:layer.opacity,detail:layer.detail,seed:layer.seed,bgMode:'solid',gradientAngle:0,transparentBg:true}}
async function ensureAssetImage(asset,layer=null){if(!asset)return null;let key='';let src='';if(asset.kind==='svg'){let mode=layer?.svgColorMode||asset.svgColorMode||'original';let tint=(layer?.colors?.[1]||asset.tint||'#9B87F5').toUpperCase();key=`${mode}|${tint}`;src=mode==='single'?svgToDataUrl(recolorSvg(asset.svgText||'',tint)):asset.dataURL}else{key='original';src=asset.dataURL}if(asset._img&&asset._cacheKey===key)return asset._img;asset._cacheKey=key;asset._img=await loadImage(src);return asset._img}
function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
function svgToDataUrl(svg){return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`}
function recolorSvg(text,color){try{let doc=new DOMParser().parseFromString(text,'image/svg+xml');doc.querySelectorAll('*').forEach(el=>{['fill','stroke'].forEach(attr=>{let v=el.getAttribute(attr);if(v&&v!=='none')el.setAttribute(attr,color)});let style=el.getAttribute('style');if(style){style=style.replace(/fill\s*:\s*([^;]+)/gi,`fill:${color}`).replace(/stroke\s*:\s*([^;]+)/gi,`stroke:${color}`);el.setAttribute('style',style)}});return new XMLSerializer().serializeToString(doc)}catch{return text}}
function fitSize(img,size,mode='motif'){let ratio=img.width&&img.height?img.width/img.height:1;if(mode==='tile'){if(ratio>=1)return [size,size/ratio];return [size*ratio,size]}if(ratio>=1)return [size,size/ratio];return [size*ratio,size]}
function renderUploadedLayer(target,w,h,layer,scale,seamless=false){let asset=userAssets.find(v=>v.id===layer.assetId);if(!asset||!asset._img)return;let img=asset._img;let rng=mulberry32(hashString(layer.seed+':upload'));let size=layer.size*scale, gap=layer.gap*scale, step=Math.max(8,size+gap), jit=(seamless?0:layer.jitter/100*size*.42), rot=layer.rotation*Math.PI/180, op=layer.opacity/100;let [dw,dh]=fitSize(img,size,layer.renderMode);target.save();target.globalAlpha=op;target.translate(w/2,h/2);target.rotate(rot);target.translate(-w/2,-h/2);for(let y=-step;y<h+step;y+=step){for(let x=-step;x<w+step;x+=step){let xx=x+(seamless?0:jitterRand(rng,jit));let yy=y+(seamless?0:jitterRand(rng,jit));if(layer.renderMode==='tile'){target.drawImage(img,xx,yy,dw,dh)}else{target.drawImage(img,xx-dw/2,yy-dh/2,dw,dh)}}}target.restore()}
function jitterRand(rng,a){return (rng()-.5)*2*a}
function hashString(str){let h=2166136261>>>0;str=String(str);for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function mulberry32(seed){return function(){let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
async function ensureVisibleAssets(){let needs=[];for(let layer of state.layers){if(layer.enabled&&layer.sourceType==='uploaded'&&layer.assetId){let asset=userAssets.find(v=>v.id===layer.assetId);if(asset)needs.push(ensureAssetImage(asset,layer).catch(()=>null))}}if(needs.length)await Promise.all(needs)}
async function renderMain(){await ensureVisibleAssets();ctx.save();ctx.setTransform(1,0,0,1,0,0);drawBackground(ctx,canvas.width,canvas.height);ctx.restore();for(let layer of state.layers){if(!layer.enabled)continue;if(layer.sourceType==='builtin'){PE.render(ctx,canvas.width,canvas.height,layerToPatternState(layer,false),getPreset(layer.presetId),canvas.width/2000)}else renderUploadedLayer(ctx,canvas.width,canvas.height,layer,canvas.width/2000,false)}updateSelected()}
function updateSelected(){let layer=currentLayer();if(layer.sourceType==='builtin'){let p=getPreset(layer.presetId);$('#selectedCategory').textContent=p.category;$('#selectedName').textContent=p.name;$('#selectedDesc').textContent=`${layer.name} 편집 중 · ${p.desc}`}else{let asset=userAssets.find(v=>v.id===layer.assetId);$('#selectedCategory').textContent='업로드 에셋';$('#selectedName').textContent=asset?asset.name:'에셋 없음';$('#selectedDesc').textContent=`${layer.name} 편집 중 · ${layer.renderMode==='tile'?'반복 타일':'모티프 반복'}`}}
function setupCategories(){let wrap=$('#categoryTabs');wrap.innerHTML='';categories().forEach(c=>{let b=document.createElement('button');b.className='tab'+(c===activeCategory?' active':'');b.textContent=c;b.onclick=()=>{activeCategory=c;setupCategories();renderPatternList()};wrap.appendChild(b)})}
function filteredPresets(){let q=$('#searchInput').value.trim().toLowerCase();return PE.presets.filter(p=>(activeCategory==='전체'||p.category===activeCategory)&&(!$('#favoriteOnly').checked||favorites.has(p.id))&&(!q||`${p.name} ${p.category} ${p.desc} ${p.id}`.toLowerCase().includes(q)))}
function thumbnailLayerForPreset(p){let layer={...currentLayer(),presetId:p.id,sourceType:'builtin'};let d=PE.defaults[p.id]||{};Object.assign(layer,d);return layer}
function renderPatternList(){let list=$('#patternList'),items=filteredPresets();$('#patternCount').textContent=`${PE.presets.length}가지 패턴 · 현재 ${items.length}개`;list.innerHTML='';items.forEach(p=>{let b=document.createElement('button');b.className='pattern-card'+(currentLayer().sourceType==='builtin'&&p.id===currentLayer().presetId?' active':'');let fav=document.createElement('button');fav.type='button';fav.className='pattern-fav'+(favorites.has(p.id)?' on':'');fav.textContent=favorites.has(p.id)?'★':'☆';fav.title='즐겨찾기';fav.onclick=e=>{e.stopPropagation();toggleFavorite(p.id)};let c=document.createElement('canvas');c.width=c.height=180;let thumbLayer=thumbnailLayerForPreset(p);PE.render(c.getContext('2d'),180,180,layerToPatternState(thumbLayer,false),p,180/720);let st=document.createElement('strong');st.textContent=p.name;let sm=document.createElement('small');sm.textContent=p.desc;b.append(fav,c,st,sm);b.onclick=()=>selectPatternForActiveLayer(p.id);list.appendChild(b)})}
function toggleFavorite(id){favorites.has(id)?favorites.delete(id):favorites.add(id);persistAll();renderPatternList();renderFavoritePreview()}
function selectPatternForActiveLayer(id){let layer=currentLayer();layer.sourceType='builtin';layer.presetId=id;let d=PE.defaults[id]||{};Object.assign(layer,d);layer.seed=Math.floor(Math.random()*1e9);persistAll();syncLayerUI();renderPatternList();renderMain()}
function setupLayerTabs(){let wrap=$('#layerTabs');wrap.innerHTML='';state.layers.forEach((layer,i)=>{let b=document.createElement('button');b.className='layer-tab'+(i===activeLayerIndex?' active':'');b.textContent=`${layer.name}`;b.onclick=()=>{activeLayerIndex=i;setupLayerTabs();syncLayerUI();renderPatternList();renderAssetList();renderMain()};wrap.appendChild(b)});$('#activeLayerLabel').textContent=`현재 편집: ${state.layers[activeLayerIndex].name}`}
function renderLayerSummary(){let wrap=$('#layerSummary');wrap.innerHTML='';state.layers.forEach((layer,i)=>{let row=document.createElement('button');row.className='layer-chip'+(i===activeLayerIndex?' active':'');let name=document.createElement('div');name.innerHTML=`<strong>${layer.name}</strong><small>${layer.enabled?'활성':'비활성'} · ${layer.sourceType==='builtin'?(getPreset(layer.presetId).name):(userAssets.find(v=>v.id===layer.assetId)?.name||'업로드 에셋')}</small>`;let bullet=document.createElement('span');bullet.className='bullet';bullet.style.opacity=layer.enabled?1:.35;let eye=document.createElement('button');eye.type='button';eye.className='mini-btn';eye.textContent=layer.enabled?'끄기':'켜기';eye.onclick=e=>{e.stopPropagation();layer.enabled=!layer.enabled;persistAll();syncLayerUI();renderMain()};row.append(bullet,name,eye);row.onclick=()=>{activeLayerIndex=i;setupLayerTabs();syncLayerUI();renderPatternList();renderAssetList();renderMain()};wrap.appendChild(row)})}
function renderColorInputs(colors,onChange,prefix='c'){let wrap=document.createElement('div');wrap.className='color-grid';colorMeta.forEach((meta,i)=>{let row=document.createElement('div');row.className='color-row';let label=document.createElement('div');label.className='color-label';label.textContent=`${meta[0]} · ${meta[1]}`;let picker=document.createElement('input');picker.type='color';picker.value=colors[i]||'#FFFFFF';picker.dataset.i=i;let text=document.createElement('input');text.type='text';text.value=(colors[i]||'#FFFFFF').toUpperCase();text.maxLength=7;let drop=document.createElement('button');drop.type='button';drop.className='dropper';drop.textContent='💧';drop.title='화면에서 색상 추출';row.append(label,picker,text,drop);picker.oninput=()=>{colors[i]=picker.value.toUpperCase();text.value=colors[i];onChange()};text.oninput=()=>{if(/^#[0-9a-fA-F]{6}$/.test(text.value)){colors[i]=text.value.toUpperCase();picker.value=colors[i];onChange()}};drop.onclick=async()=>{if(!window.EyeDropper){toast('이 브라우저는 화면 스포이드를 지원하지 않아.');return}try{let res=await new EyeDropper().open();colors[i]=res.sRGBHex.toUpperCase();picker.value=colors[i];text.value=colors[i];onChange()}catch{}};wrap.appendChild(row)});return wrap}
function renderBgColorInputs(){let root=$('#bgColorGrid');root.innerHTML='';['배경 A','배경 B'].forEach((labelText,i)=>{let row=document.createElement('div');row.className='color-row';let label=document.createElement('div');label.className='color-label';label.textContent=labelText;let picker=document.createElement('input');picker.type='color';picker.value=state.bg.colors[i];let text=document.createElement('input');text.type='text';text.value=state.bg.colors[i];text.maxLength=7;let drop=document.createElement('button');drop.type='button';drop.className='dropper';drop.textContent='💧';picker.oninput=()=>{state.bg.colors[i]=picker.value.toUpperCase();text.value=state.bg.colors[i];persistAll();renderMain()};text.oninput=()=>{if(/^#[0-9a-fA-F]{6}$/.test(text.value)){state.bg.colors[i]=text.value.toUpperCase();picker.value=state.bg.colors[i];persistAll();renderMain()}};drop.onclick=async()=>{if(!window.EyeDropper){toast('이 브라우저는 화면 스포이드를 지원하지 않아.');return}try{let res=await new EyeDropper().open();state.bg.colors[i]=res.sRGBHex.toUpperCase();picker.value=state.bg.colors[i];text.value=state.bg.colors[i];persistAll();renderMain()}catch{}};row.append(label,picker,text,drop);root.appendChild(row)})}
function renderLayerEditor(){let layer=currentLayer();let root=$('#layerEditor');root.innerHTML='';let card=document.createElement('div');card.className='layer-editor-card';let top=document.createElement('div');top.className='layer-editor-grid';top.innerHTML=`<div class="inline-row"><strong>${layer.name}</strong><label class="switch-row compact"><input id="layerEnabledToggle" type="checkbox" ${layer.enabled?'checked':''}/> 사용</label></div><div class="control-subtitle">패턴 카드 선택은 현재 활성 레이어에 바로 적용돼.</div>`;
  let sourceRow=document.createElement('div');sourceRow.className='source-type-row';let builtinBtn=document.createElement('button');builtinBtn.className='ghost'+(layer.sourceType==='builtin'?' active':'');builtinBtn.textContent='내장 패턴';let uploadBtn=document.createElement('button');uploadBtn.className='ghost'+(layer.sourceType==='uploaded'?' active':'');uploadBtn.textContent='업로드 에셋';builtinBtn.onclick=()=>{layer.sourceType='builtin';persistAll();syncLayerUI();renderPatternList();renderMain()};uploadBtn.onclick=()=>{layer.sourceType='uploaded';persistAll();syncLayerUI();renderAssetList();renderMain()};sourceRow.append(builtinBtn,uploadBtn);top.appendChild(sourceRow);
  if(layer.sourceType==='builtin'){
    let sel=document.createElement('div');sel.className='selectish';let p=getPreset(layer.presetId);sel.textContent=`현재 선택: ${p.name} · ${p.category}`;top.appendChild(sel)
  }else{
    let box=document.createElement('div');box.className='layer-editor-grid';let assetSel=document.createElement('select');let placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='업로드 에셋 선택';assetSel.appendChild(placeholder);userAssets.forEach(a=>{let op=document.createElement('option');op.value=a.id;op.textContent=`${a.name} (${a.kind==='svg'?'SVG':'PNG/JPG'})`;if(a.id===layer.assetId)op.selected=true;assetSel.appendChild(op)});assetSel.onchange=()=>{layer.assetId=assetSel.value;persistAll();renderAssetList();renderMain()};let renderMode=document.createElement('select');[['motif','모티프 반복'],['tile','반복 타일']].forEach(([v,t])=>{let op=document.createElement('option');op.value=v;op.textContent=t;if(layer.renderMode===v)op.selected=true;renderMode.appendChild(op)});renderMode.onchange=()=>{layer.renderMode=renderMode.value;persistAll();renderMain()};box.appendChild(labeled('업로드 에셋',assetSel));box.appendChild(labeled('배치 방식',renderMode));let selectedAsset=userAssets.find(v=>v.id===layer.assetId);if(!selectedAsset){let help=document.createElement('div');help.className='control-subtitle';help.textContent='왼쪽 업로드 박스에 투명 PNG/SVG를 올린 뒤, 여기서 선택하면 반복 패턴으로 쓸 수 있어.';box.appendChild(help)}if(selectedAsset?.kind==='svg'){let svgMode=document.createElement('select');[['original','원본 색상 유지'],['single','레이어 패턴 A 색으로 단색 변환']].forEach(([v,t])=>{let op=document.createElement('option');op.value=v;op.textContent=t;if((layer.svgColorMode||'original')===v)op.selected=true;svgMode.appendChild(op)});svgMode.onchange=async()=>{layer.svgColorMode=svgMode.value;selectedAsset._img=null;persistAll();await ensureAssetImage(selectedAsset,layer).catch(()=>null);renderAssetList();renderMain()};box.appendChild(labeled('SVG 색상 모드',svgMode))}
    top.appendChild(box)
  }
  let colorTitle=document.createElement('div');colorTitle.className='section-title-row';colorTitle.innerHTML='<h3>레이어 색상</h3><button id="applyPaletteToLayer" class="mini-btn" type="button">팔레트 랜덤</button>';top.appendChild(colorTitle);
  top.appendChild(renderColorInputs(layer.colors,()=>{persistAll();let asset=userAssets.find(v=>v.id===layer.assetId);if(asset&&asset.kind==='svg'){asset._img=null;ensureAssetImage(asset,layer).then(renderMain)}persistAll();renderPatternListDebounced();renderAssetList();renderMain()}));
  let controls=document.createElement('div');controls.className='layer-editor-grid';controls.appendChild(sliderRow('패턴 크기','size',layer.size,12,260,'px',v=>layer.size=v));controls.appendChild(sliderRow('간격','gap',layer.gap,0,160,'px',v=>layer.gap=v));controls.appendChild(sliderRow('불규칙함','jitter',layer.jitter,0,100,'%',v=>layer.jitter=v));controls.appendChild(sliderRow('회전','rotation',layer.rotation,-45,45,'°',v=>layer.rotation=v));controls.appendChild(sliderRow('선 두께','stroke',layer.stroke,1,18,'px',v=>layer.stroke=v));controls.appendChild(sliderRow('패턴 투명도','opacity',layer.opacity,0,100,'%',v=>layer.opacity=v));controls.appendChild(sliderRow('포인트/디테일','detail',layer.detail,0,100,'%',v=>layer.detail=v));top.appendChild(controls);card.appendChild(top);root.appendChild(card);
  $('#layerEnabledToggle').onchange=e=>{layer.enabled=e.target.checked;persistAll();renderLayerSummary();renderMain()};
  $('#applyPaletteToLayer').onclick=()=>{let p=palettePresets[Math.floor(Math.random()*palettePresets.length)];layer.colors=[...p];persistAll();syncLayerUI();renderPatternListDebounced();renderMain()}
}
function labeled(labelText,node){let wrap=document.createElement('label');wrap.textContent=labelText;wrap.appendChild(node);return wrap}
function sliderRow(label,key,val,min,max,unit,setter){let wrap=document.createElement('label');let valueSpan=document.createElement('span');valueSpan.textContent=`${val}${unit}`;wrap.textContent=label+' ';wrap.appendChild(valueSpan);let input=document.createElement('input');input.type='range';input.min=min;input.max=max;input.value=val;input.oninput=()=>{setter(+input.value);valueSpan.textContent=`${input.value}${unit}`;if(key!=='seed'){currentLayer().seed=Math.floor(Math.random()*1e9)}persistAll();renderPatternListDebounced();renderMain()};wrap.appendChild(input);return wrap}
function syncLayerUI(){setupLayerTabs();renderLayerSummary();renderLayerEditor();updateSelected();persistAll()}
function renderPatternListDebounced(){clearTimeout(thumbTimer);thumbTimer=setTimeout(renderPatternList,160)}

async function handleAssetFiles(files){let added=0,addedAssets=[];for(let file of files){try{let asset=await fileToAsset(file);userAssets.unshift(asset);addedAssets.unshift(asset);added++}catch(e){console.error(e)}}if(added){let layer=currentLayer();if(addedAssets[0]){layer.sourceType='uploaded';layer.assetId=addedAssets[0].id;layer.renderMode=layer.renderMode||'motif'}persistAll();syncLayerUI();renderAssetList();toast(`${added}개 에셋을 추가했고, 현재 레이어에 바로 연결했어.`);renderMain()}}
function readFileAsDataURL(file){return new Promise((resolve,reject)=>{let fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsDataURL(file)})}
function readFileAsText(file){return new Promise((resolve,reject)=>{let fr=new FileReader();fr.onload=()=>resolve(fr.result);fr.onerror=reject;fr.readAsText(file)})}
async function fileToAsset(file){let kind=file.type.includes('svg')||file.name.toLowerCase().endsWith('.svg')?'svg':'raster';let dataURL=await readFileAsDataURL(file);let asset={id:uid('asset'),name:file.name,kind,dataURL,addedAt:Date.now(),svgText:'',svgColorMode:'original',tint:'#9B87F5'};if(kind==='svg')asset.svgText=await readFileAsText(file);await ensureAssetImage(asset,{svgColorMode:'original',colors:['#FFF','#9B87F5','#B9D7FF','#BFAAF2']}).catch(()=>null);return asset}
function renderAssetList(){let wrap=$('#assetList');wrap.innerHTML='';if(!userAssets.length){wrap.innerHTML='<div class="reference-preview empty">아직 업로드한 에셋이 없어. 위의 업로드 박스에 투명 PNG/SVG를 넣으면 바로 패턴용으로 사용할 수 있어.</div>';return}userAssets.forEach(asset=>{let card=document.createElement('div');card.className='asset-card';let thumb=asset._img?document.createElement('img'):document.createElement('div');thumb.className='asset-thumb'+(asset._img?'':' fallback');if(asset._img)thumb.src=asset._img.src;else thumb.textContent=asset.kind==='svg'?'◇':'▣';let meta=document.createElement('div');meta.className='asset-meta';meta.innerHTML=`<strong>${asset.name}</strong><small>${asset.kind==='svg'?'SVG (색상 변환 가능)':'PNG/JPG (크기·간격 조절 가능)'}</small>`;let acts=document.createElement('div');acts.className='asset-actions';let assign=document.createElement('button');assign.className='mini-btn';assign.textContent='현재 레이어에 적용';assign.onclick=()=>{let layer=currentLayer();layer.sourceType='uploaded';layer.assetId=asset.id;persistAll();syncLayerUI();renderAssetList();renderMain()};let del=document.createElement('button');del.className='mini-btn';del.textContent='삭제';del.onclick=()=>{if(!confirm('이 에셋을 삭제할까?'))return;userAssets=userAssets.filter(a=>a.id!==asset.id);state.layers.forEach(layer=>{if(layer.assetId===asset.id){layer.assetId='';layer.sourceType='builtin'}});persistAll();renderAssetList();syncLayerUI();renderMain()};acts.append(assign,del);card.append(thumb,meta,acts);if(currentLayer().sourceType==='uploaded'&&currentLayer().assetId===asset.id)card.style.borderColor='#9b87f0';wrap.appendChild(card)})}

function renderFavoritePreview(){let wrap=$('#favoritePreview');wrap.innerHTML='';if(!favorites.size){wrap.innerHTML='<span class="muted mini-copy">즐겨찾기한 패턴이 아직 없어.</span>';return}[...favorites].slice(0,18).forEach(id=>{let p=getPreset(id);let chip=document.createElement('button');chip.className='chip';chip.textContent=`★ ${p.name}`;chip.onclick=()=>{activeCategory='전체';setupCategories();selectPatternForActiveLayer(id);renderPatternList()};wrap.appendChild(chip)})}
function renderSavedPresets(){let wrap=$('#savedPresetList');wrap.innerHTML='';if(!myPresets.length){wrap.innerHTML='<div class="muted mini-copy">저장된 내 프리셋이 아직 없어.</div>';return}myPresets.forEach(item=>{let card=document.createElement('div');card.className='preset-card';let info=document.createElement('div');info.innerHTML=`<strong>${item.name}</strong><small>${new Date(item.savedAt).toLocaleString()}</small>`;let acts=document.createElement('div');acts.className='preset-actions';let apply=document.createElement('button');apply.className='mini-btn';apply.textContent='적용';apply.onclick=()=>{state=mergeState(clone(item.state));activeLayerIndex=0;persistAll();syncAll()};let del=document.createElement('button');del.className='mini-btn';del.textContent='삭제';del.onclick=()=>{myPresets=myPresets.filter(v=>v.id!==item.id);persistAll();renderSavedPresets();toast('프리셋을 삭제했어.')};acts.append(apply,del);card.append(info,acts);wrap.appendChild(card)})}
function saveCurrentPreset(){let name=prompt('저장할 프리셋 이름을 입력해줘.','내 패턴 프리셋');if(!name)return;myPresets.unshift({id:uid('preset'),name:name.trim()||'내 프리셋',savedAt:Date.now(),state:clone(stripStateForSave(state))});myPresets=myPresets.slice(0,40);persistAll();renderSavedPresets();toast('현재 설정을 내 프리셋에 저장했어.')}

function setupPalettes(){/* reserved for future UI विस्तार */}
function syncGlobalControls(){renderBgColorInputs();$('#bgMode').value=state.bg.mode;$('#transparentBg').checked=state.bg.transparent;$('#gradientAngle').value=state.bg.gradientAngle;$('#gradientAngleVal').textContent=`${state.bg.gradientAngle}°`;$('#gradientControls').style.display=state.bg.mode==='linear'&&!state.bg.transparent?'block':'none';$('#exportW').value=state.exportW;$('#exportH').value=state.exportH;$('#tileW').value=state.tileW;$('#tileH').value=state.tileH}
function setZoom(v){zoom=clamp(v,.3,1.6);$('#zoomText').textContent=Math.round(zoom*100)+'%';canvas.style.width=`min(${72*zoom}vh, ${78*zoom}vw)`}
function randomizeAll(){let palette=palettePresets[Math.floor(Math.random()*palettePresets.length)];state.bg.colors=[palette[0],palette[1]];state.layers.forEach((layer,i)=>{let candidates=PE.presets.filter(p=>!$('#favoriteOnly').checked||favorites.has(p.id));let p=(candidates.length?candidates:PE.presets)[Math.floor(Math.random()*Math.max(1,(candidates.length?candidates:PE.presets).length))];layer.sourceType='builtin';layer.presetId=p.id;let d=PE.defaults[p.id]||{};Object.assign(layer,d);layer.colors=shuffle(palette.concat()).slice(0,4);while(layer.colors.length<4)layer.colors.push(palette[0]);layer.size=clamp((d.size??layer.size)+(i*10),12,220);layer.gap=clamp((d.gap??layer.gap)+Math.floor(Math.random()*30),0,120);layer.jitter=clamp((d.jitter??20)+Math.floor(Math.random()*40),0,100);layer.rotation=Math.floor(-18+Math.random()*36);layer.opacity=clamp(100-i*22,20,100);layer.detail=Math.floor(25+Math.random()*70);layer.enabled=i<2||Math.random()>.5;layer.seed=Math.floor(Math.random()*1e9)});persistAll();syncAll();toast('레이어·색·패턴을 랜덤으로 조합했어.')}
async function exportPNG(seamless=false){let w=clamp(+($('#exportW').value)||2000,256,6000),h=clamp(+($('#exportH').value)||2000,256,6000);if(seamless){w=clamp(+($('#tileW').value)||512,64,4000);h=clamp(+($('#tileH').value)||512,64,4000)}state.exportW=w;state.exportH=h;if(seamless){state.tileW=w;state.tileH=h}persistAll();let out=document.createElement('canvas');out.width=w;out.height=h;let octx=out.getContext('2d');drawBackground(octx,w,h);for(let layer of state.layers){if(!layer.enabled)continue;if(layer.sourceType==='builtin'){PE.render(octx,w,h,layerToPatternState(layer,seamless),getPreset(layer.presetId),w/2000)}else{let asset=userAssets.find(v=>v.id===layer.assetId);if(asset){await ensureAssetImage(asset,layer).catch(()=>null);renderUploadedLayer(octx,w,h,layer,w/2000,seamless)}}}let blob=await new Promise(r=>out.toBlob(r,'image/png'));if(!blob){toast('PNG 생성에 실패했어.');return}let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=seamless?`cute-pattern-seamless-${w}x${h}.png`:`cute-pattern-${w}x${h}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500);toast(`${w}×${h} ${seamless?'심리스 타일':'PNG'}를 저장했어.`)}

async function handleReferenceFile(file){let dataURL=await readFileAsDataURL(file);let img=await loadImage(dataURL);let prev=$('#referencePreview');prev.innerHTML='';let el=document.createElement('img');el.src=dataURL;prev.classList.remove('empty');prev.appendChild(el);referencePalette=extractPalette(img,6);renderReferencePalette()}
function extractPalette(img,count=6){let c=document.createElement('canvas');let max=90;let ratio=Math.min(max/img.width,max/img.height,1);c.width=Math.max(16,Math.floor(img.width*ratio));c.height=Math.max(16,Math.floor(img.height*ratio));let x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0,c.width,c.height);let data=x.getImageData(0,0,c.width,c.height).data;let buckets=new Map();for(let i=0;i<data.length;i+=4){let a=data[i+3];if(a<180)continue;let r=Math.round(data[i]/32)*32,g=Math.round(data[i+1]/32)*32,b=Math.round(data[i+2]/32)*32;if(r>248&&g>248&&b>248)continue;let key=[clamp(r,0,255),clamp(g,0,255),clamp(b,0,255)].join(',');buckets.set(key,(buckets.get(key)||0)+1)}let ranked=[...buckets.entries()].sort((a,b)=>b[1]-a[1]).map(([k])=>k.split(',').map(Number));let out=[];for(let rgb of ranked){if(out.every(v=>colorDistance(v,rgb)>42)){out.push(rgb);if(out.length>=count)break}}while(out.length<count)out.push([255,244,248]);return out.map(rgbToHex)}
function colorDistance(a,b){let dr=a[0]-b[0],dg=a[1]-b[1],db=a[2]-b[2];return Math.sqrt(dr*dr+dg*dg+db*db)}
function rgbToHex([r,g,b]){return '#'+[r,g,b].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase()}
function renderReferencePalette(){let wrap=$('#referencePalette');wrap.innerHTML='';if(!referencePalette.length)return;let box=document.createElement('div');box.className='swatch-pack';let row=document.createElement('div');row.className='swatch-row';referencePalette.forEach(c=>{let s=document.createElement('div');s.className='swatch';s.style.background=c;s.title=c;row.appendChild(s)});let actions=document.createElement('div');actions.className='preset-actions';let toLayer=document.createElement('button');toLayer.className='mini-btn';toLayer.textContent='현재 레이어에 적용';toLayer.onclick=()=>{let layer=currentLayer();layer.colors=[referencePalette[0],referencePalette[1]||referencePalette[0],referencePalette[2]||referencePalette[1]||referencePalette[0],referencePalette[3]||referencePalette[2]||referencePalette[1]||referencePalette[0]];persistAll();syncLayerUI();renderMain()};let toBg=document.createElement('button');toBg.className='mini-btn';toBg.textContent='배경에 적용';toBg.onclick=()=>{state.bg.colors=[referencePalette[0],referencePalette[1]||referencePalette[0]];persistAll();syncGlobalControls();renderMain()};let toBoth=document.createElement('button');toBoth.className='mini-btn';toBoth.textContent='배경+현재 레이어';toBoth.onclick=()=>{state.bg.colors=[referencePalette[0],referencePalette[1]||referencePalette[0]];let layer=currentLayer();layer.colors=[referencePalette[0],referencePalette[1]||referencePalette[0],referencePalette[2]||referencePalette[1]||referencePalette[0],referencePalette[3]||referencePalette[2]||referencePalette[1]||referencePalette[0]];persistAll();syncAll()};actions.append(toLayer,toBg,toBoth);box.append(row,actions);wrap.appendChild(box)}

function bindGlobalControls(){
  $('#searchInput').oninput=renderPatternList;
  $('#favoriteOnly').onchange=renderPatternList;
  $('#uploadAssetBtn').onclick=()=>$('#assetInput').click();
  $('#assetDropzone').onclick=()=>$('#assetInput').click();
  ['dragenter','dragover'].forEach(evt=>$('#assetDropzone').addEventListener(evt,e=>{e.preventDefault();$('#assetDropzone').classList.add('dragover')}));
  ['dragleave','drop'].forEach(evt=>$('#assetDropzone').addEventListener(evt,e=>{e.preventDefault();$('#assetDropzone').classList.remove('dragover')}));
  $('#assetDropzone').addEventListener('drop',e=>{const files=[...(e.dataTransfer?.files||[])];if(files.length)handleAssetFiles(files)});
  $('#assetInput').onchange=e=>{handleAssetFiles([...e.target.files]);e.target.value=''};
  $('#uploadReferenceBtn').onclick=()=>$('#referenceInput').click();
  $('#referenceInput').onchange=e=>{if(e.target.files[0])handleReferenceFile(e.target.files[0]);e.target.value=''};
  $('#bgMode').onchange=e=>{state.bg.mode=e.target.value;persistAll();syncGlobalControls();renderMain()};
  $('#transparentBg').onchange=e=>{state.bg.transparent=e.target.checked;persistAll();syncGlobalControls();renderMain()};
  $('#gradientAngle').oninput=e=>{state.bg.gradientAngle=+e.target.value;$('#gradientAngleVal').textContent=`${state.bg.gradientAngle}°`;persistAll();renderMain()};
  $('#randomizeAll').onclick=randomizeAll;
  $('#resetBtn').onclick=()=>{if(!confirm('현재 설정을 초기화할까?'))return;state=makeInitialState();activeLayerIndex=0;persistAll();syncAll();toast('초기 상태로 되돌렸어.')};
  $('#savePresetBtn').onclick=saveCurrentPreset;
  $('#duplicateLayerBtn').onclick=()=>{let src=currentLayer();let targetIndex=(activeLayerIndex+1)%3;state.layers[targetIndex]=clone(src);state.layers[targetIndex].name=`레이어 ${targetIndex+1}`;state.layers[targetIndex].seed=Math.floor(Math.random()*1e9);persistAll();syncAll();toast(`${src.name} 설정을 ${state.layers[targetIndex].name}에 복제했어.`)};
  $('#exportBtn').onclick=()=>exportPNG(false);
  $('#exportBtn2').onclick=()=>exportPNG(false);
  $('#exportTileBtn').onclick=()=>exportPNG(true);
  $('#exportTileBtn2').onclick=()=>exportPNG(true);
  $('#zoomIn').onclick=()=>setZoom(zoom+.1);
  $('#zoomOut').onclick=()=>setZoom(zoom-.1);
  $('#exportW').oninput=e=>{state.exportW=clamp(+e.target.value||2000,256,6000);if($('#lockSquare').checked){state.exportH=state.exportW;$('#exportH').value=state.exportH}persistAll()};
  $('#exportH').oninput=e=>{state.exportH=clamp(+e.target.value||2000,256,6000);if($('#lockSquare').checked){state.exportW=state.exportH;$('#exportW').value=state.exportW}persistAll()};
  $('#tileW').oninput=e=>{state.tileW=clamp(+e.target.value||512,64,4000);if($('#lockTileSquare').checked){state.tileH=state.tileW;$('#tileH').value=state.tileH}persistAll()};
  $('#tileH').oninput=e=>{state.tileH=clamp(+e.target.value||512,64,4000);if($('#lockTileSquare').checked){state.tileW=state.tileH;$('#tileW').value=state.tileW}persistAll()};
}
function syncAll(){syncGlobalControls();syncLayerUI();renderPatternList();renderAssetList();renderFavoritePreview();renderSavedPresets();renderMain()}

loadLocal();
bindGlobalControls();
setupCategories();
setupLayerTabs();
syncAll();
setZoom(1);
